### ISSUE TITLE
Extract audio only when mosaic is set to have audio support

### ISSUE THREAD

**Issue by mauricioabreu** [mauricioabreu/mosaic-video#1]
Currently, every mosaic configuration is retrieved from the following struct:

```go
Mosaic struct {
	Name      string  `json:"name"`
	Medias    []Media `json:"medias"`
	WithAudio bool    `json:"with_audio"`
}
```

`WithAudio` field should be respected while firing the ffmpeg command.

**Comment by rafiramadhana** [comment]
> WithAudio field should be respected while firing the ffmpeg command.

is this related to ffmpeg's `-an` flag?

ref: https://superuser.com/a/268986

PS. sry I haven't used ffmpeg before

**Comment by mauricioabreu** [comment]
@rafiramadhana I think the part of the command you are talking about is another option. For the command we are currently using, I guess we need to remove the `"-map", "1:a",`
