### ISSUE TITLE
Use a lib to map environment variables

### ISSUE THREAD

**Issue by mauricioabreu** [mauricioabreu/mosaic-video#18]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Currently, we are parsing env configs in a struct managed entirely by ourselves, calling `os.Getenv` without any kind of validation.

Some libs like [env](https://github.com/caarlos0/env) and [envconfig](https://github.com/kelseyhightower/envconfig) are designed to move away this burden from developers.

**Describe alternatives you've considered**
I did not consider any alternatives other than the ones above but feel free to bring your ideas.

**Comment by luiscovelo** [comment]
Another quite used library in community it's [viper](https://github.com/spf13/viper).

**Comment by Hoega** [comment]
I tried to implement Viper, but I realized it requires a default configuration file. Therefore, I not sure if it is the best option solely for reading environment variables.

**Comment by luiscovelo** [comment]
Hello @Hoega,

I analyzed those packages that @mauricioabreu mentioned, but i missed the option to unmarshall another types like .yaml or .json files, even live watching changes file.

It would be more interesting we use a most versatility library to avoid refactor in the future.

Can you'd to analyze viper again or others libraries that make senses with our goal?
