### ISSUE TITLE
Run linter on CI

### ISSUE THREAD

**Issue by mauricioabreu** [mauricioabreu/mosaic-video#19]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
We already have a command to run the linter locally. It would be great if the linter could run on CI.
Today we have a considerable amount of warnings, I'm not sure if we should fix them or apply some kind of checkpoint (to run the linter after a specific commit.

**Comment by luiscovelo** [comment]
Well, 

I would like to remove all of warnings that can possible, in my option, we can to add this verification before the build stage.
Later, we can create a conduct code or similar thing, for those who want contribute to the project, follow the rules.

**Comment by mauricioabreu** [comment]
@luiscovelo agreed!

**Comment by mauricioabreu** [comment]
@luiscovelo do you plan to open another PR incluind the linter in the CI workflow?

**Comment by luiscovelo** [comment]
@mauricioabreu,

Yes, i'll work on it as soon as possible.

**Comment by luiscovelo** [comment]
See this pull request #22.
