### ISSUE TITLE
Implementing local file system storage

### ISSUE THREAD

**Issue by mauricioabreu** [mauricioabreu/mosaic-video#24]
**Is your feature request related to a problem? Please describe.**
No changes needed.

**Describe the solution you'd like**

Currently, the program pushes all content through HTTP to an uploader, which then saves it in a storage backend.

Another option is to enable saving the files locally. Users can then expose the path (where the files are written) via a web server.

This diagram shows how users could take advantage of the local storage backend:

![local_storage](https://github.com/mauricioabreu/mosaic-video/assets/1437542/7e5c5570-52f1-4315-aa5e-d973ef410f0b)

**Describe alternatives you've considered**
No changes needed.

**Additional context**
Pros:
* A major strength of this approach is that external storage is not necessary, reducing costs and simplifying the process.
Cons:
* Implementing service discovery and a web server is required for a CDN to know where to fetch the content from.

**Comment by mauricioabreu** [comment]
Assigned to @mauricioabreu

**Comment by luiscovelo** [comment]
Nice @mauricioabreu,

Whether you need help, assign some task to me.

**Comment by luiscovelo** [comment]
Solves in #25.
