### ISSUE TITLE
Allow using videos on demand (loop)

### ISSUE THREAD

**Issue by mauricioabreu** [mauricioabreu/mosaic-video#28]
**Is your feature request related to a problem? Please describe.**
No changes needed.

**Describe the solution you'd like**
A mosaic might be generated from videos on demand instead of using HLS playlists.

Imagine you are streaming a mosaic with 3 videos: 2 live streams and 1 promo video (with a QR code, for example) linking your website. This promo video could be a VoD.

**Describe alternatives you've considered**
No changes needed.

**Additional context**
No changes needed.

**Comment by luiscovelo** [comment]
Solves in #30 pull request.
